services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    container_name: wp
    image: wordpress:6.4.1-php8.1-apache
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-admin:/var/www/html/wp-admin
      - ./wp-includes:/var/www/html/wp-includes
    ports:
      - 80:80
    restart: no
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WP_PROXY_HOST=http://wpad.staempfli.ch
      - WP_PROXY_PORT=8080
      - WP_PROXY_BYPASS_HOSTS=localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - WP_DEBUG=true
      - HTTP_PROXY=http://wpad.staempfli.ch:8080
      - HTTPS_PROXY=http://wpad.staempfli.ch:8080
      - NO_PROXY=localhost,127.0.0.1
